services:

  backend:
    restart: always
    build: ./backend/
    container_name: backend
    env_file: ./.env
    volumes:
      - sqlite:/var/lib/sqlite
      - ./backend/src/public:/var/www/server/public
    networks:
      - back
    develop:
      watch:
        - path: ./backend/src
          action: rebuild
          target: /var/www/server

  frontend:
    restart: always
    build: ./frontend/
    container_name: frontend
    env_file: ./.env
    depends_on:
      - backend
    networks:
      - front
      - back
    develop:
      watch:
        - path: ./frontend/src
          action: rebuild
          target: /var/www/html

  modsecurity:
    restart: always
    build: ./modsecurity/
    container_name: modsecurity
    volumes:
      - cert:/etc/nginx/conf/ssl
    ports:
      - "8080:80"
      - "8081:443"
    networks:
      - front
      - back
      - web
      - nginx_prom_export
    depends_on:
      - frontend
      - backend
    develop:
      watch:
        - path: ./frontend/srcs
          action: rebuild
          target: /var/www/html
        - path: ./frontend/conf/nginx.conf
          action: rebuild
          target: /etc/nginx/nginx.conf

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - modsecurity_logs:/var/log/nginx/access.log
    networks:
      - monitoring
      - nginx_prom_export

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./monitoring/conf/grafana/defaults.ini:/usr/share/grafana/conf/defaults.ini
      - ./monitoring/conf/grafana/grafana-provisioning:/etc/grafana/provisioning
    networks:
      - monitoring
    ports:
      - "3001:3001"
    depends_on:
      - prometheus

  nginx_prom_export:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx_prom_export
    networks:
      - nginx_prom_export
    depends_on:
      - prometheus
      - modsecurity
    command: ["--nginx.scrape-uri=http://modsecurity:801/stub_status"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    env_file:
    - .env
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    volumes:
      - ./elk/logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - modsecurity_logs:/var/log/nginx/access.log:ro
    depends_on:
      - elasticsearch
      - modsecurity
    env_file:
      - .env
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    volumes:
      - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  web:
    driver: bridge
  monitoring:
  back:
  front:
  nginx_prom_export:
  elk:

volumes:
  sqlite:
    name: sqlite
  cert:
    name: cert
  avatars:
    name: avatars
  es_data:
  modsecurity_logs: