services:

  backend:
    restart: always
    build: ./backend/
    container_name: backend
    env_file: ./.env
    volumes:
      - sqlite:/var/lib/sqlite
      - ./backend/src/public:/var/www/server/public
    networks:
      - db
    develop:
      watch:
        - path: ./backend/src
          action: rebuild
          target: /var/www/server

  frontend:
    restart: always
    build: ./frontend/
    container_name: frontend
    env_file: ./.env
    depends_on:
      - backend
    networks:
      - web
      - db
    develop:
      watch:
        - path: ./frontend/src
          action: rebuild
          target: /var/www/html

  modsecurity:
    restart: always
    build: ./modsecurity/
    container_name: modsecurity
    volumes:
      - cert:/etc/nginx/conf/ssl
    ports:
      - "8080:80"
      - "8081:443"
    networks:
      - web
      - db
      - transcendence
      - nginx_prom_export
    depends_on:
      - frontend
      - backend
    develop:
      watch:
        - path: ./frontend/srcs
          action: rebuild
          target: /var/www/html
        - path: ./frontend/conf/nginx.conf
          action: rebuild
          target: /etc/nginx/nginx.conf

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
      - nginx_prom_export

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./monitoring/conf/grafana/defaults.ini:/usr/share/grafana/conf/defaults.ini
      - ./monitoring/conf/grafana/grafana-provisioning:/etc/grafana/provisioning
    networks:
      - monitoring
    ports:
      - "3001:3001"
    depends_on:
      - prometheus

  nginx_prom_export:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx_prom_export
    networks:
      - nginx_prom_export
    depends_on:
      - prometheus
      - modsecurity
    command: ["--nginx.scrape-uri=http://modsecurity:801/stub_status"]

networks:
  transcendence:
    driver: bridge
  monitoring:
  db:
  web:
  nginx_prom_export:

volumes:
  sqlite:
    name: sqlite
  cert:
    name: cert
  avatars:
    name: avatars
