services:

  backend:
    # restart: always
    build: ./backend/
    container_name: backend
    # env_file: ./.env
    ports:
      - "3000:3000"
    volumes:
      - sqlite:/var/lib/sqlite
    networks:
      - backend

  frontend:
    restart: always
    build: ./frontend/
    container_name: frontend
    # env_file: ./.env
    ports:
      - "8443:443"
    volumes:
      - front_data:/var/www/html
    networks:
      - transcendence
      - backend

networks:
  transcendence:
    driver: bridge
  backend:
    driver: bridge

volumes:
  sqlite:
    name: sqlite
  front_data:
    name: front_data
