services:

  backend:
    # restart: always
    build: ./backend/
    container_name: backend
    env_file: ./.env
    volumes:
      - sqlite:/var/lib/sqlite
    networks:
      - db

  frontend:
    restart: always
    build: ./frontend/
    container_name: frontend
    env_file: ./.env
    depends_on:
      - backend
    volumes:
      - front_data:/var/www/html
    networks:
      - transcendence
      - web

networks:
  transcendence:
    driver: bridge
  db:
  web:

volumes:
  sqlite:
    name: sqlite
  front_data:
    name: front_data
