global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  query_log_file: /prometheus/logs/prometheus.log
  scrape_failure_log_file: /prometheus/logs/prometheus_error.log
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
scrape_configs:
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: 
        - 'nginx_prom_export:9113'
