global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  query_log_file: /prometheus/logs/prometheus.log
  scrape_failure_log_file: /prometheus/logs/prometheus_error.log

rule_files:
  - 'alert.rules.yml'
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'grafana'
    scheme: http
    metrics_path: /admin/grafana/metrics
    static_configs:
      - targets: ['grafana:3001']
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: 
        - 'nginx_prom_export:9113'
        labels:
          instance: 'ModSec'
  - job_name: 'elasticsearch'
    scheme: http
    static_configs:
      - targets: ['elasticsearch_exporter:9114']
  - job_name: 'node'
    static_configs:
    - targets: ['node_exporter:9100']
  - job_name: 'logstash'
    static_configs:
    - targets: ['logstash-exporter:9198']
    metrics_path: /metrics