[package]
name = "serious"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
env = "1.0.1"
reqwest = {version = "0.12.24", features = ["json"]}
serde_json = "1.0.145"
terminal = "0.2.1"
tokio = { version = "1", features = ["full"] }
