- pipeline.id: modsec
  path.config: "/usr/share/logstash/pipeline/modsec.conf"

- pipeline.id: grafana
  path.config: "/usr/share/logstash/pipeline/grafana.conf"

- pipeline.id: logstash
  path.config: "/usr/share/logstash/pipeline/self.conf"

- pipeline.id: elasticsearch
  path.config: "/usr/share/logstash/pipeline/elasticsearch.conf"